[build]
  # Build command for Netlify
  command = "echo 'Frontend build completed'"
  
  # Directory to publish
  publish = "frontend"
  
  # Functions directory (if using Netlify Functions)
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Java version (if needed for build process)
  JAVA_VERSION = "21"

# Redirect rules for SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.yourdomain.com;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache HTML files for shorter time
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Environment variables (set these in Netlify dashboard)
[context.production.environment]
  API_URL = "https://your-backend-api.com"
  NODE_ENV = "production"

[context.deploy-preview.environment]
  API_URL = "https://staging-api.yourdomain.com"
  NODE_ENV = "development"

[context.branch-deploy.environment]
  API_URL = "https://staging-api.yourdomain.com"
  NODE_ENV = "development"

# Form handling (if using Netlify Forms)
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Plugin configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.9
    best-practices = 0.8
    seo = 0.8

# Edge functions (if using Netlify Edge Functions)
[edge_functions]
  directory = "netlify/edge-functions"
