name: Test Workflow

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    test:
        name: Test Job
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Test step
              run: |
                  echo "Hello from GitHub Actions!"
                  echo "This is a test workflow"
                  echo "Current date: $(date)"

            - name: List files
              run: |
                  echo "Files in repository:"
                  ls -la
